version: '3'

services:
  php:
    # img-74_php, 
    image: lar74-php:latest
    volumes:
      - './www:/var/www/html'
    # для использования localhost локальной машины
    # network_mode: "host"
    restart: always
  nginx:
    image: nginx:latest
    container_name: laravelNX
    ports:
      - 80:80
    volumes:
      - './www:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - './data/mysql:/var/lib/mysql'
      - './docker/mysql:/etc/mysql/conf.d'
    user: "1000"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bitrix
      - TZ=Europe/Moscow
    ports:
      - 3306:3306  
  mailhog:
      image: mailhog/mailhog:latest
      ports:
        - "1025:1025"
        - "8025:8025"