#!/bin/sh

# Сделать бэкап и добавить его в git
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

FNAME=$CURRENT_DIR/data/backup/backup_db_git.sql

docker exec mysql sh -c 'exec mysqldump --databases bitrix -uroot -p"root"' > "$FNAME"

exec git add .
